config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"

  get "subscriptions/new", to: "subscriptions#new", as: "new_subscription"
  get "subscriptions/:id", to: "subscriptions#show"
  post "subscriptions", to: "subscriptions#create"

  resources :boxes

  get "settings", to: "settings#index"

  get "sign-up", to: "registration#new"
  post "sign-up", to: "registration#create"
  
  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "companies", to: "company#index"
  get "companies/new", to: "company#new", as: "new_company"
  post "companies", to: "company#create"
  get "companies/:id", to: "company#show"
  get "companies/:id/edit", to: "company#edit", as: "edit_company"
  put "companies/:id", to: "company#update", as: "company"

  get "products", to: "products#index"
  get "companies/:company_id/products/new", to: "products#new", as: "new_company_product"
  post "companies/:company_id/products", to: "products#create", as: "company_products"
  get "products/:id", to: "products#show"
  get "products/:id/edit", to: "products#edit", as: "edit_product"
  put "products/:id", to: "products#update", as: "product"

  get "profile", to: "users#edit", as: "edit_user"
  patch "profile", to: "users#update", as: "users"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "policies", to: "policies#index"
  get "terms", to: "terms#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :companies, :dependent => :destroy
    has_many :boxes
    
    # compares virtual attributes password and password_confirmation
    # if same, hashes password and saves value to password_digest
    has_secure_password

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
    validates :password, allow_blank: true, length: { in: 6..20 }
    validates :username, uniqueness: true, allow_blank: true, length: { minimum: 1, maximum: 10, too_short: "%{count} characters is the minimum allowed", too_long: "%{count} characters is the maximum allowed" }, format: { with: /\A[a-zA-Z0-9_]+\z/, message: "only allows letters, numbers, and underscores" }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action   :require_user_logged_in, :get_user
    
    def edit
    end

    def update
        @user.username = user_params[:username]
        if @user.save
            redirect_to edit_user_path, notice: "Profile updated"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:username)
    end

    def get_user
        @user = Current.user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :title do %>
  Profile
<% end %>

<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
    
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
    
      <%= form_with class: "space-y-6", model: @user, builder: TailwindFormHelper::TailwindFormBuilder, method: "patch", url: users_path do |form| %>
        
        <%= render partial: "shared/form_errors", locals: { form: form } %>
        
        <div>
          <%= form.label :username %>
          <div class="mt-1">
            <%= form.text_field :username %>
          </div>
        </div>

        <div>
          <%= form.label :password %>
          <div class="mt-1">
            <%= link_to  "Change your login info here", edit_password_path, class: "w-full py-2 sm:text-sm underline" %>
          </div>
        </div>

        <div>
          <%= form.submit "Save changes" %>
        </div>
      <% end %>

    </div>
  </div>
</div>