config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"

  get "subscriptions/new", to: "subscriptions#new", as: "new_subscription"
  get "subscriptions/:id", to: "subscriptions#show"
  post "subscriptions", to: "subscriptions#create"

  resources :boxes

  get "settings", to: "settings#index"

  get "sign-up", to: "registration#new"
  post "sign-up", to: "registration#create"
  
  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "companies", to: "company#index"
  get "companies/new", to: "company#new", as: "new_company"
  post "companies", to: "company#create"
  get "companies/:id", to: "company#show"
  get "companies/:id/edit", to: "company#edit", as: "edit_company"
  put "companies/:id", to: "company#update", as: "company"

  get "products", to: "products#index"
  get "companies/:company_id/products/new", to: "products#new", as: "new_company_product"
  post "companies/:company_id/products", to: "products#create", as: "company_products"
  get "products/:id", to: "products#show"
  get "products/:id/edit", to: "products#edit", as: "edit_product"
  put "products/:id", to: "products#update", as: "product"

  get "profile", to: "users#edit", as: "edit_user"
  patch "profile", to: "users#update", as: "users"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "policies", to: "policies#index"
  get "terms", to: "terms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/box.rb
class Box < ApplicationRecord
    belongs_to :user
    belongs_to :company
    belongs_to :product

    enum :delivery_location, [ :shinjuku ]
    enum :status, [ :open, :requires_action, :closed ]

    validates :company_id, presence: true
    validates :product_id, presence: true
    validates :units_number, presence: true
    validates :delivery_location, presence: true
    validates :bulk_delivery_fee, presence: true
    validates :single_delivery_fee, presence: true
    validates :ends_at, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
    belongs_to :user
    has_many :products
    
    validates :name, presence: true
    validates :url, uniqueness: true, allow_blank: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :company

    enum :kind, [ :shiitake, :maitake, :matsutake ]
    enum :prefecture_of_origin, [ :tokyo, :niigata, :ooita ]
    
    validates :name, presence: true
    validates :description, presence: true
    validates :kind, presence: true
    validates :prefecture_of_origin, presence: true
    validates :price, presence: true
    validates :items_per_unit, presence: true
    validates :weight_per_unit, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :companies, :dependent => :destroy
    has_many :boxes
    
    # compares virtual attributes password and password_confirmation
    # if same, hashes password and saves value to password_digest
    has_secure_password

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
    validates :password, allow_blank: true, length: { in: 6..20 }
    validates :username, uniqueness: true, allow_blank: true, length: { minimum: 1, maximum: 10, too_short: "%{count} characters is the minimum allowed", too_long: "%{count} characters is the maximum allowed" }, format: { with: /\A[a-zA-Z0-9_]+\z/, message: "only allows letters, numbers, and underscores" }
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :require_user_logged_in

  def index
    @boxes = Current.user.boxes

  end

  def new
    @box = Box.new
    @companies = Current.user.companies

    # Company selected by user
    @company = Current.user.companies.find_by_id(box_params[:company_id])
    if @company
      @products = @company.products
    else 
      @products = []
    end
  end

  def show
    @box = Current.user.boxes.find(params[:id])
    p @box
    @company = Current.user.companies.find_by_id(@box.company_id)
    @product = @company.products.find_by_id(@box.product_id)
  end

  def create
    @box = Current.user.boxes.create(box_params)
    if @box.save 
      redirect_to boxes_path, notice: "Successfully created box campaign"
    else
      # Reinitalize variables
      @companies = Current.user.companies
      @products = []
      render :new, status: :unprocessable_entity
    end
  end 

  private 

  def box_params
    params.fetch(:box, {}).permit(
      :company_id, 
      :product_id,
      :units_number,
      :delivery_location,
      :bulk_delivery_fee,
      :single_delivery_fee,
      :ends_at
    )
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    layout "public"
    
    def index
        
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
    layout "public"
    
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def tailwind_primary_link_to(text, href)
        options = "w-full flex items-center justify-center bg-red-400 hover:bg-red-500 px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white"
        "<a href='#{href}' class='#{options}'>#{text}</a>".html_safe
    end

    def tailwind_secondary_link_to(text, href)
        options = "w-full flex items-center justify-center bg-slate-800 hover:bg-slate-900 px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white"
        "<a href='#{href}' class='#{options}'>#{text}</a>".html_safe
    end

    def tailwind_white_link_to(text, href)
        options = "inline-flex items-center px-6 py-3 border border-gray-300 shadow-sm text-base font-medium rounded-md text-gray-900 bg-white hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500"
        "<a href='#{href}' class='#{options}'>#{text}</a>".html_safe
    end

    def tailwind_footer_link_to(text, href)
        options = "text-base text-gray-500 hover:text-gray-900"
        "<a href='#{href}' class='#{options}'>#{text}</a>".html_safe
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <%= render partial: "shared/head" %>

  <body class="h-full">
        <div>
        <% if Current.user %>
          <%= render partial: "shared/private_page" %>
        <% else %>
         <%# ToDo(rw): show an unauthorized view %>
        <% end %>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html class="h-full">
	<%= render partial: "shared/head" %>

  <body class="h-full">
    <div>
		<%= render partial: "shared/navbar" %>
		<main>
			<div class="py-6">
				<%= render partial: "shared/flash" %>
				<div class="min-h-screen">
          <div class="max-w-7xl mx-auto py-4 sm:px-6 md:px-8">
            <h1 class="text-2xl font-semibold text-gray-900">
              <%= yield :title %>
            </h1>
          </div>
					<%= yield %>
				</div>
				<%= render partial: "shared/footer" %>
			</div>
		</main>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:alert] %>
	<div class="rounded-md bg-yellow-50 p-4">
		<div class="flex">
			<div class="flex-shrink-0">
				<!-- Heroicon name: solid/check-circle -->
				<svg class="h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
					<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
				</svg>
			</div>
			<div class="ml-3">
				<p class="text-sm font-medium text-yellow-700"> <%= flash[:alert] %></p>
			</div>
		</div>
	</div>
<% elsif flash[:notice] %>
	<div class="rounded-md bg-green-50 p-4">
		<div class="flex">
			<div class="flex-shrink-0">
				<!-- Heroicon name: solid/check-circle -->
				<svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
					<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
				</svg>
			</div>
			<div class="ml-3">
				<p class="text-sm font-medium text-green-800"> <%= flash[:notice] %></p>
			</div>
		</div>
	</div>
<% elsif flash[:alert] %>
	<div class="rounded-md bg-red-50 p-4">
		<div class="flex">
			<div class="flex-shrink-0">
				<!-- Heroicon name: solid/x-circle -->
				<svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
					<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
				</svg>
			</div>
			<div class="ml-3">
				<p class="text-sm font-medium text-red-800"> <%= flash[:notice] %></p>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white mt-24" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="mx-auto py-12 px-4 sm:px-6 lg:py-6 lg:px-8">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <div class="space-y-8 xl:col-span-1">
        <img class="h-10" src="https://tailwindui.com/img/logos/workflow-mark-gray-300.svg" alt="Company name">
        <p class="text-gray-500 text-base">Making the world a better place through constructing elegant hierarchies.</p>
        <div class="flex space-x-6">

          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">Twitter</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
            </svg>
          </a>
          
        </div>
      </div>
      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Legal</h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <%= tailwind_footer_link_to "Privacy policy", policies_path %>
              </li>

            </ul>
          </div>
          <%# <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Support</h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Pricing </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Documentation </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Guides </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> API Status </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Company</h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> About </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Blog </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Jobs </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Press </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Partners </a>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">Legal</h3>
            <ul role="list" class="mt-4 space-y-4">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Claim </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Privacy </a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900"> Terms </a>
              </li>
            </ul>
          </div> %>
        </div>
      </div>
    </div>
    <div class="mt-12 border-t border-gray-200 pt-8">
      <p class="text-base text-gray-400 xl:text-center">&copy; 2020 Workflow, Inc. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_form_errors.html.erb
<% unless form.object.nil?%>
	<% if form.object.errors.any? %>
		<div class="rounded-md bg-red-50 p-4">
			<div class="flex">
				<div class="flex-shrink-0">
					<!-- Heroicon name: solid/x-circle -->
					<svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
						<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
					</svg>
				</div>
				<div class="ml-3">
					<h3 class="text-sm font-medium text-red-800">There were <%= form.object.errors.size %> errors with your submission</h3>
					<div class="mt-2 text-sm text-red-700">
						<ul role="list" class="list-disc pl-5 space-y-1">
							<% form.object.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% end %> 

app/views/shared/_head.html.erb
<head>
	<title>testbox</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

	<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
	<%= javascript_importmap_tags %>
	<%= javascript_include_tag "application", "data-track-turbo": "true", defer: true %>
</head>

app/views/shared/_navbar.html.erb
  <header>
    <div data-controller="toggle" class="relative bg-white">
      <div class="flex justify-between items-center mx-auto px-4 py-6 sm:px-6 md:justify-start md:space-x-10 lg:px-8">
        <div class="flex justify-start lg:w-0 lg:flex-1">
          <%= link_to root_path do %>
            <span class="sr-only">Workflow</span>
            <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-purple-600-to-indigo-600.svg" alt="">
          <% end %>
        </div>
        <div class="-mr-2 -my-2 md:hidden">
          <button data-action="click->toggle#toggle" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
            <span class="sr-only">Open menu</span>
            <!-- Heroicon name: outline/menu -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </div>

        <nav class="hidden md:flex space-x-10">
          <div class="relative">
          <!-- Item active: "text-gray-900", Item inactive: "text-gray-500" -->
          
          <%# <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900"> Pricing </a>
          <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900"> Partners </a>
          <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900"> Company </a> %>
        </nav>
        <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0 space-x-3">
          <%= tailwind_white_link_to "Log in", sign_in_path %>
          <%= link_to "Sign up", sign_up_path, class: "inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-slate-800 hover:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500" %>
        </div>
        
      </div>

      <!--
        Mobile menu, show/hide based on mobile menu state.

        Entering: "duration-200 ease-out"
          From: "opacity-0 scale-95"
          To: "opacity-100 scale-100"
        Leaving: "duration-100 ease-in"
          From: "opacity-100 scale-100"
          To: "opacity-0 scale-95"
      -->
      <div data-toggle-target="content" class="absolute z-30 top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden hidden">
        <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
          <div class="pt-5 pb-6 px-5">
            <div class="flex items-center justify-between">
              <div>
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-purple-600-to-indigo-600.svg" alt="Workflow">
              </div>
              <div class="-mr-2">
                <button data-action="click->toggle#toggle" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
                  <span class="sr-only">Close menu</span>
                  <!-- Heroicon name: outline/x -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div class="mt-6">
              <nav class="grid grid-cols-1 gap-7">
                <%# <a href="#" class="-m-3 p-3 flex items-center rounded-lg hover:bg-gray-50">
                  <div class="flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-md bg-gradient-to-r from-purple-600 to-indigo-600 text-white">
                    <!-- Heroicon name: outline/inbox -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
                    </svg>
                  </div>
                  <div class="ml-4 text-base font-medium text-gray-900">Inbox</div>
                </a>

                <a href="#" class="-m-3 p-3 flex items-center rounded-lg hover:bg-gray-50">
                  <div class="flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-md bg-gradient-to-r from-purple-600 to-indigo-600 text-white">
                    <!-- Heroicon name: outline/annotation -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                    </svg>
                  </div>
                  <div class="ml-4 text-base font-medium text-gray-900">Messaging</div>
                </a>

                <a href="#" class="-m-3 p-3 flex items-center rounded-lg hover:bg-gray-50">
                  <div class="flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-md bg-gradient-to-r from-purple-600 to-indigo-600 text-white">
                    <!-- Heroicon name: outline/chat-alt-2 -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
                    </svg>
                  </div>
                  <div class="ml-4 text-base font-medium text-gray-900">Live Chat</div>
                </a>

                <a href="#" class="-m-3 p-3 flex items-center rounded-lg hover:bg-gray-50">
                  <div class="flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-md bg-gradient-to-r from-purple-600 to-indigo-600 text-white">
                    <!-- Heroicon name: outline/question-mark-circle -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                  <div class="ml-4 text-base font-medium text-gray-900">Knowledge Base</div>
                </a>
              </nav>
            </div> %>
          </div>

          <div class="py-6 px-5">
            <%# <div class="grid grid-cols-2 gap-4">
              <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Pricing </a>
              <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Partners </a>
              <a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Company </a>
            </div> %>
            <div class="mt-6">
              <%= tailwind_secondary_link_to "Sign up", sign_up_path %>
              <p class="mt-6 text-center text-base font-medium text-gray-500">
                Existing customer?
                <%= link_to "Log in", sign_in_path %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

app/views/shared/_sidebar.html.erb
<%# Static sidebar for desktop%>
<div class="hidden md:flex md:w-48 md:flex-col md:fixed md:inset-y-0">
    <%# Sidebar component, swap this element with another sidebar if you like%>
    <div class="flex flex-col flex-grow pt-5 bg-indigo-700 overflow-y-auto">
        <div class="mt-5 flex-1 flex flex-col">
            <nav class="flex-1 px-2 pb-4 space-y-1">
                <li class="text-indigo-100 hover:bg-indigo-600 group flex items-center px-2 py-2 text-sm font-medium rounded-md">
                    <%= link_to "Settings", settings_path %>
                </li>
            </nav>
        </div>
    </div>
</div>

app/views/shared/_sidepanel.html.erb
<div class="bg-white overflow-hidden shadow rounded-lg divide-y divide-gray-200">
  <div class="px-4 py-5 sm:px-6">
    <!-- Content goes here -->
    <!-- We use less vertical padding on card headers on desktop than on body sections -->
  </div>
  <div class="px-4 py-5 sm:p-6">
    <!-- Content goes here -->
  </div>
</div>