config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"

  get "subscriptions/new", to: "subscriptions#new", as: "new_subscription"
  get "subscriptions/:id", to: "subscriptions#show"
  post "subscriptions", to: "subscriptions#create"

  resources :boxes

  get "settings", to: "settings#index"

  get "sign-up", to: "registration#new"
  post "sign-up", to: "registration#create"
  
  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "companies", to: "company#index"
  get "companies/new", to: "company#new", as: "new_company"
  post "companies", to: "company#create"
  get "companies/:id", to: "company#show"
  get "companies/:id/edit", to: "company#edit", as: "edit_company"
  put "companies/:id", to: "company#update", as: "company"

  get "products", to: "products#index"
  get "companies/:company_id/products/new", to: "products#new", as: "new_company_product"
  post "companies/:company_id/products", to: "products#create", as: "company_products"
  get "products/:id", to: "products#show"
  get "products/:id/edit", to: "products#edit", as: "edit_product"
  put "products/:id", to: "products#update", as: "product"

  get "profile", to: "users#edit", as: "edit_user"
  patch "profile", to: "users#update", as: "users"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "policies", to: "policies#index"
  get "terms", to: "terms#index"
end

app/models/company.rb
class Company < ApplicationRecord
    belongs_to :user
    has_many :products
    
    validates :name, presence: true
    validates :url, uniqueness: true, allow_blank: true
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
    before_action :require_user_logged_in, :get_companies

    def index
    end
    
    def new
        @company = Company.new
    end

    def edit 
        @company = @companies.find(params[:id])
    end

    def show 
        @company = @companies.find(params[:id]) 
        @products = @company.products.all       
    end

    def create
        @company = @companies.create(company_params)
        if @company.save
            redirect_to company_path(@company), notice: "Successfully added company"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update 
        @company = @companies.find(params[:id])
        if @company.update(company_params)
            redirect_to company_path(@company), notice: "Successfully updated company"
        else 
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def company_params
        params.require(:company).permit(
            :name, 
            :url
        )
    end

    def get_companies
        @companies = Current.user.companies
    end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/edit.html.erb
<% content_for :title do %>
  Update company
<% end %>

<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with class: "space-y-6", model: @company, builder: TailwindFormHelper::TailwindFormBuilder, method: "put", url: company_path(@company) do |form| %>
        
        <%= render partial: "shared/form_errors", locals: { form: form } %>

        <div>
          <%= form.label :name %>
          <div class="mt-1">
            <%= form.text_field :name %>
          </div>
        </div>

        <div>
          <%= form.label :url %>
          <div class="mt-1">
            <%= form.text_field :url %>
          </div>
        </div>

        <div>
          <%= form.submit "Save changes" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/company/index.html.erb
<% content_for :title do %>
  Companies
<% end %>
 
<div class="mt-8 max-w-3xl mx-auto grid grid-cols-1 gap-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
  <div class="space-y-6 lg:col-start-1 lg:col-span-2">

    <!-- Description list-->
    <section aria-labelledby="applicant-information-title">
      
      <!-- This example requires Tailwind CSS v2.0+ -->
      <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">

        <% @companies.each do |company| %>

        <div class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3 hover:border-gray-400 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
          <%# <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div> %>
          <div class="flex-1 min-w-0">
            <%= link_to company_path(company.id), class: "focus:outline-none" do %>
              <span class="absolute inset-0" aria-hidden="true"></span>
              <p class="text-sm font-medium text-gray-900"><%= company.name %></p>
              <p class="text-sm text-gray-500 truncate"><%= company.url %></p>
            <% end %>
          </div>
        </div>

        <% end %>
      </div>

      </section>
    </div>

    <section aria-labelledby="timeline-title" class="lg:col-start-3 lg:col-span-1">
      <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:px-6">
        <h2 id="timeline-title" class="text-lg font-medium text-gray-900">Action panel</h2>
        
        <ul role="list" class="divide-y divide-gray-200">
          <li class="py-4 flex">
            <%= tailwind_primary_link_to "Add company", new_company_path %>
          </li>
        </ul>

      </div>
    </section>
  
</div>

app/views/company/new.html.erb
<% content_for :title do %>
  Add a company
<% end %>

<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with class: "space-y-6", model: @company, builder: TailwindFormHelper::TailwindFormBuilder, url: companies_path do |form| %>
        
        <%= render partial: "shared/form_errors", locals: { form: form } %>

        <div>
          <%= form.label :name %>
          <div class="mt-1">
            <%= form.text_field :name %>
          </div>
        </div>

        <div>
          <%= form.label :url %>
          <div class="mt-1">
            <%= form.text_field :url %>
          </div>
        </div>

        <div>
          <%= form.submit "Add company" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/company/show.html.erb
<% content_for :title do %>
  Company details
<% end %>
 
<div class="mt-8 max-w-3xl mx-auto grid grid-cols-1 gap-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
  
    <div class="space-y-6 lg:col-start-1 lg:col-span-2">
    
    <!-- Description list-->
    <section aria-labelledby="applicant-information-title">
        
      <!-- This example requires Tailwind CSS v2.0+ -->
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">

      <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
        <dl class="sm:divide-y sm:divide-gray-200">
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Company name</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @company.name %></dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Company website</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @company.url %></dd>
        </div>
          
      </div>

    </section>
      <section aria-labelledby="company-products">
        <div class="max-w-7xl mx-auto py-4">
          <h1 class="text-2xl font-semibold text-gray-900">Company products</h1>
        </div>
        
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">

          <% @products.each do |product| %>
            <div class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3 hover:border-gray-400 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
              <%# <div class="flex-shrink-0">
                  <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </div> %>
              <div class="flex-1 min-w-0">
                <%= link_to product_path(product.id), class: "focus:outline-none" do %>
                  <span class="absolute inset-0" aria-hidden="true"></span>
                  <p class="text-sm font-medium text-gray-900"><%= product.name %></p>
                  <p class="text-sm text-gray-500 truncate"><%= product.description %></p>
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
    </section>
    
  </div>

  <section aria-labelledby="timeline-title" class="lg:col-start-3 lg:col-span-1">
    <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:px-6">
      <h2 id="timeline-title" class="text-lg font-medium text-gray-900">Action panel</h2>
      
      <ul role="list" class="divide-y divide-gray-200">
        <li class="py-4 flex">
          <%= tailwind_primary_link_to "Edit company", edit_company_path(@company) %>
        </li>
      </ul>

      <ul role="list" class="divide-y divide-gray-200">
        <li class="py-4 flex">
          <%= tailwind_primary_link_to "Add product", new_company_product_path(@company) %>
        </li>
      </ul>

    </div>
  </section>

</div>