config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"

  get "subscriptions/new", to: "subscriptions#new", as: "new_subscription"
  get "subscriptions/:id", to: "subscriptions#show"
  post "subscriptions", to: "subscriptions#create"

  resources :boxes

  get "settings", to: "settings#index"

  get "sign-up", to: "registration#new"
  post "sign-up", to: "registration#create"
  
  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "companies", to: "company#index"
  get "companies/new", to: "company#new", as: "new_company"
  post "companies", to: "company#create"
  get "companies/:id", to: "company#show"
  get "companies/:id/edit", to: "company#edit", as: "edit_company"
  put "companies/:id", to: "company#update", as: "company"

  get "products", to: "products#index"
  get "companies/:company_id/products/new", to: "products#new", as: "new_company_product"
  post "companies/:company_id/products", to: "products#create", as: "company_products"
  get "products/:id", to: "products#show"
  get "products/:id/edit", to: "products#edit", as: "edit_product"
  put "products/:id", to: "products#update", as: "product"

  get "profile", to: "users#edit", as: "edit_user"
  patch "profile", to: "users#update", as: "users"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "policies", to: "policies#index"
  get "terms", to: "terms#index"
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :company

    enum :kind, [ :shiitake, :maitake, :matsutake ]
    enum :prefecture_of_origin, [ :tokyo, :niigata, :ooita ]
    
    validates :name, presence: true
    validates :description, presence: true
    validates :kind, presence: true
    validates :prefecture_of_origin, presence: true
    validates :price, presence: true
    validates :items_per_unit, presence: true
    validates :weight_per_unit, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action   :require_user_logged_in, :get_company

    def index
    end
    
    def new
        @product = Product.new
    end

    def edit 
        @product = Product.find(params[:id])
    end

    def create
        @product = @company.products.create(product_params)
        if @product.save 
            redirect_to product_path(@product), notice: "Successfully added product"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @product = Product.find(params[:id])
    end

    private

    def product_params
        params.require(:product).permit(
            :name, 
            :description, 
            :kind, 
            :prefecture_of_origin, 
            :price, 
            :items_per_unit, 
            :weight_per_unit
        )
    end

    def get_company
        if params[:company_id]
            @company = Current.user.companies.find(params[:company_id])
        end
    end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/edit.html.erb
<% content_for :title do %>
  Edit product
<% end %>

<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with class: "space-y-6", model: @product, builder: TailwindFormHelper::TailwindFormBuilder, url: product_path(@product) do |form| %>
        
        <%= render partial: "shared/form_errors", locals: { form: form } %>

        <div>
          <%= form.label :name %>
          <div class="mt-1">
            <%= form.text_field :name %>
          </div>
        </div>

        <div>
          <%= form.label :description %>
          <div class="mt-1">
            <%= form.text_field :description %>
          </div>
        </div>

         <div>
          <%= form.label :kind %>
          <div class="mt-1">
            <%= form.select :kind, options_for_select(Product.kinds.keys), include_blank: "Select kind" %>
          </div>
        </div>

        <div>
          <%= form.label :prefecture_of_origin %>
          <div class="mt-1">
            <%= form.select :prefecture_of_origin, options_for_select(Product.prefecture_of_origins.keys), include_blank: "Select prefecture" %>
          </div>
        </div>

        <div>
          <%= form.label :price %>
          <div class="mt-1">
            <%= form.text_field :price %>
          </div>
        </div>

        <div>
          <%= form.label :items_per_unit %>
          <div class="mt-1">
            <%= form.text_field :items_per_unit %>
          </div>
        </div>

         <div>
          <%= form.label :weight_per_unit %>
          <div class="mt-1">
            <%= form.text_field :weight_per_unit %>
          </div>
        </div>

        <div>
          <%= form.submit "Save changes" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/products/new.html.erb
<% content_for :title do %>
  Add product
<% end %>

<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with class: "space-y-6", model: @product, builder: TailwindFormHelper::TailwindFormBuilder, url: company_products_path do |form| %>
        
        <%= render partial: "shared/form_errors", locals: { form: form } %>

        <div>
          <%= form.label :name %>
          <div class="mt-1">
            <%= form.text_field :name %>
          </div>
        </div>

        <div>
          <%= form.label :description %>
          <div class="mt-1">
            <%= form.text_field :description %>
          </div>
        </div>

         <div>
          <%= form.label :kind %>
          <div class="mt-1">
            <%= form.select :kind, options_for_select(Product.kinds.keys), include_blank: "Select kind" %>
          </div>
        </div>

        <div>
          <%= form.label :prefecture_of_origin %>
          <div class="mt-1">
            <%= form.select :prefecture_of_origin, options_for_select(Product.prefecture_of_origins.keys), include_blank: "Select prefecture" %>
          </div>
        </div>

        <div>
          <%= form.label :price %>
          <div class="mt-1">
            <%= form.text_field :price %>
          </div>
        </div>

        <div>
          <%= form.label :items_per_unit %>
          <div class="mt-1">
            <%= form.text_field :items_per_unit %>
          </div>
        </div>

         <div>
          <%= form.label :weight_per_unit %>
          <div class="mt-1">
            <%= form.text_field :weight_per_unit %>
          </div>
        </div>

        <div>
          <%= form.submit "Add product" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/products/show.html.erb
<% content_for :title do %>
  Product details
<% end %>

<div class="mt-8 max-w-3xl mx-auto grid grid-cols-1 gap-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
  
    <div class="space-y-6 lg:col-start-1 lg:col-span-2">
    
    <!-- Description list-->
    <section aria-labelledby="applicant-information-title">
        
      <!-- This example requires Tailwind CSS v2.0+ -->
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">

      <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
        <dl class="sm:divide-y sm:divide-gray-200">
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Product name</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.name %></dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Product description</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.description %></dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Product kind</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.kind %></dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Prefecture of origin</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.prefecture_of_origin %></dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Price</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.price%></dd>
        </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Price with tax</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.price_with_tax%></dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Items per unit</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.items_per_unit%></dd>
        </div>
          <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Weight per unit</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @product.weight_per_unit%></dd>
        </div>
        
      </div>

    </section>
  </div>

  <section aria-labelledby="timeline-title" class="lg:col-start-3 lg:col-span-1">
    <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:px-6">
      <h2 id="timeline-title" class="text-lg font-medium text-gray-900">Action panel</h2>
      
      <ul role="list" class="divide-y divide-gray-200">
        <li class="py-4 flex">
          <%= tailwind_primary_link_to "Edit product", edit_product_path(@product) %>
        </li>
      </ul>

    </div>
  </section>

</div>